package pages;

import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import pojos.Customer;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;

import dao.BookDaoImpl;
import dao.CustomerDaoImpl;

/**
 * Servlet implementation class AunthenticationServlet
 */
@WebServlet(description = "User validation servlet", urlPatterns = { "/aunthenticate", "/validate" }, loadOnStartup = 1)
public class AunthenticationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private CustomerDaoImpl dao;
	private BookDaoImpl bookDao;
	

	/**
	 * @see Servlet#init(ServletConfig)
	 */
	@Override
	public void init() throws ServletException {
		try {
			dao = new CustomerDaoImpl();
			bookDao = new BookDaoImpl();
		}catch(Exception e) {
			throw new ServletException("err in init of"+getClass().getName(), e);
		}
	}

	/**
	 * @see Servlet#destroy()
	 */
	public void destroy() {
		try{  
			dao.cleanUp();
		}catch(SQLException e) {
			throw new RuntimeException("err in destroy"+getClass().getName(), e);
		}
	}
 
	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html");
		try(PrintWriter pw = response.getWriter()){
			String email = request.getParameter("em");
			String password = request.getParameter("pass");
			Customer customer = dao.authenticateCustomer(email, password);
			
			if(customer == null) {
				pw.print("<h4>Invalid login!!! please <a href = 'login.html'>Retry</a></h4>");
			}
			else {
				// success
				//1 . Get HTTP Session from WC
				HttpSession session=request.getSession();
				System.out.println("From auth servlet Session ID "+session.getId());//unique long string generated by WC
				System.out.println("Is it a New session ? "+session.isNew());//true
				//save validated customer details under session scope
				//Method of HttpSession i/f : public void setAttribute(String attrName,Object attrValue)
				session.setAttribute("customer_dtls",customer);
				session.setAttribute("cust_dao",dao);
				session.setAttribute("book_dao",bookDao);//saved in server side heap within HttpSession object		
				//create an empty shopping cart n save it under session scope
				//what should be a data type of the cart? list<Integer> :ArrayList
				session.setAttribute("cart", new ArrayList<Integer>());
				
				response.sendRedirect("category");// MUST match with the url-pattern of the CategoryServlet
				// WC sends temp redirect resp
				// STS code : SC302 | location=category , set-cookie : cookie(nm , val) 
				//nm : JSESSIONID , value=cgfdg57653756fghd
				//|body :
				// empty
				// clnt side browser will send a NEW request : http://host:port/day4.1/category
				// method : get
				// will cookies be sent or not ? : if cookies are accepted : cookie : in req header
				// header.

			}
		}catch(Exception e) {
			throw new ServletException("err in dopost"+ getClass().getName(), e);
		}
		
	}

}
